### ISSUE TITLE
dyld Symbol not found: _SSL_library_init after upgrade to 5.4.0 on OS X Catalina

### ISSUE THREAD

**Issue by danascheider** [puma/puma#2672]
Hi folks! I chose "bug report" because it was closest to what I wanted, but I'm not sure if this is actually a bug with Puma or not. I'd really appreciate any guidance you're able to offer since I'm having to use the older version of Puma until I figure this out.

## Describe the bug

I just upgraded my Rails 6 API from Puma 5.3.2 to Puma 5.4.0. I'm using the setup that is default with Rails and haven't done any custom configuration. Everything was working fine until I upgraded. After upgrading, running any `bundle exec` command results in the following error:
```
dyld: lazy symbol binding failed: Symbol not found: _SSL_library_init
  Referenced from: /Users/danascheider/exampleproject/vendor/bundle/ruby/3.0.0/gems/puma-5.4.0/lib/puma/puma_http11.bundle
  Expected in: flat namespace

dyld: Symbol not found: _SSL_library_init
  Referenced from: /Users/danascheider/exampleproject/vendor/bundle/ruby/3.0.0/gems/puma-5.4.0/lib/puma/puma_http11.bundle
  Expected in: flat namespace
```

## Things I've Tried

I've done a lot of googling and not managed to fix the problem. I know it happens in my development environment but I'm not sure what would happen under Linux since I don't want to deploy it until it works locally. The following are things I've tried, based on my Google results, that have not worked:

* Uninstalled Puma 5.4.0, reinstalled OpenSSL (it was already on the latest version) and reinstalled Puma 5.4.0
* Ran `export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"` and `export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"`

## Puma config

I'm not using any Puma config outside of what Rails provides by default.

## Versions

I am running:

* OS X Catalina 10.15.4 on Intel MacBook Pro
* Puma 5.4.0 (upgraded from 5.3.2, which was working fine)
* Rails 6.1.4
* Ruby 3.0.2
* OpenSSL 1.1.1k (didn't work with 1.0.2r either)

My Ruby version manager is RVM. I've tried both using the default system OpenSSL (1.0.2r) and a brew-installed OpenSSL (1.1.1k) and it didn't change anything.

## To Reproduce

The bug, if that's what it is, is able to be reproduced with the minimal example you've given in this template (`bundle exec puma -C config.ru` where `config.ru` contains `run lambda { |env| [200, {"Content-Type" => "text/plain"}, ["Hello World"]] }`)

**Expected behavior**

Whatever command I've run with `bundle exec` (`rspec`, `rails server`, etc.) should run successfully as it did with Puma 5.3.2.

**Desktop (please complete the following information):**
 - OS: OS X Catalina 10.15.4
 - Puma Version 5.4.0

**Comment by MSP-Greg** [comment]
@danascheider

First, I'm rather macOS challenged.  We are running CI on macOS 10.15.7 with Ruby 3.0.2/OpenSSL 1.1.1k, and it's passing.  See:

https://github.com/puma/puma/runs/3203012762#step:9:13

I looked around, and saw https://github.com/eventmachine/eventmachine/issues/936, not sure if any of it is applicable...

**Comment by dentarg** [comment]
@danascheider can you reinstall Ruby and see if that helps?

**Comment by danascheider** [comment]
Thanks folks, yeah, I did try reinstalling Ruby and it didn't seem to help. If this isn't a known thing/nobody else is having this problem with a dev environment that's all good, I can try Dockerising the app and I imagine it'll work in that environment. I mostly just wondered if this was something you'd heard about or already knew how to solve as well as document it in case somebody else had the same problem.

**Comment by fxsalazar** [comment]
I'm having the same issue just after updating Puma as well on BigSur. Tried to reinstall openssl and everything.

**Comment by fxsalazar** [comment]
Fixed it:
- uninstall openssl and ruby
- install ruby (I'm using asdf);
- tried running `rspec` and gave the ssl-error but now it was postgresql who was complaining
- `brew reinstall postgresql`
- it works.

**Comment by dentarg** [comment]
I can use Puma 5.4.0 on macOS 10.15.7 using Ruby 3.0.2. @danascheider can you try to update macOS from 10.15.4 to the latest Catalina version?

(I've installed Ruby using [ruby-build](https://github.com/rbenv/ruby-build), but I'm switching versions using [chruby](https://github.com/postmodern/chruby))

**Comment by danascheider** [comment]
Sorry for the delay on this. I finally was able to upgrade to the latest Catalina version and now Puma 5.4.0 won't even install. I'll try uninstalling/reinstalling Ruby and will let you know what happens.

**Comment by nateberkopec** [comment]
Not sure what's going on for you @danascheider but this isn't a bug in Puma. Something is wrong with where you've got your SSL library installed. Uninstalling/reinstalling openssl via `brew`, re-linking, some combination thereof will probably fix your issue.
