### ISSUE TITLE
puma_http11 fails to build on OpenBSD 7.1

### ISSUE THREAD

**Issue by eradman** [puma/puma#2863]
**Describe the bug**

puma_http11 fails to build on OpenBSD 7.1

```
using OpenSSL pkgconfig (openssl.pc)
checking for openssl/bio.h... yes
checking for DTLS_method() in openssl/ssl.h... yes
checking for TLS_server_method() in openssl/ssl.h... yes
checking for SSL_CTX_set_min_proto_version(NULL, 0) in openssl/ssl.h... yes
checking for X509_STORE_up_ref()... yes
checking for SSL_CTX_set_ecdh_auto(NULL, 0) in openssl/ssl.h... yes
checking for SSL_get1_peer_certificate() in openssl/ssl.h... no
checking for Random.bytes... yes
creating Makefile

current directory: /home/eradman/.gem/ruby/3.1/gems/puma-5.6.4/ext/puma_http11
make DESTDIR\= clean

current directory: /home/eradman/.gem/ruby/3.1/gems/puma-5.6.4/ext/puma_http11
make DESTDIR\=
compiling http11_parser.c
compiling mini_ssl.c
mini_ssl.c:102:5: error: incomplete definition of type 'struct dh_st'
  dh->p = BN_bin2bn(dh2048_p, sizeof(dh2048_p), NULL);
  ~~^
/usr/include/openssl/ossl_typ.h:116:16: note: forward declaration of 'struct dh_st'
typedef struct dh_st DH;
               ^
mini_ssl.c:103:5: error: incomplete definition of type 'struct dh_st'
  dh->g = BN_bin2bn(dh2048_g, sizeof(dh2048_g), NULL);
  ~~^
/usr/include/openssl/ossl_typ.h:116:16: note: forward declaration of 'struct dh_st'
typedef struct dh_st DH;
               ^
mini_ssl.c:105:10: error: incomplete definition of type 'struct dh_st'
  if ((dh->p == NULL) || (dh->g == NULL)) {
       ~~^
/usr/include/openssl/ossl_typ.h:116:16: note: forward declaration of 'struct dh_st'
typedef struct dh_st DH;
               ^
mini_ssl.c:105:29: error: incomplete definition of type 'struct dh_st'
  if ((dh->p == NULL) || (dh->g == NULL)) {
                          ~~^
/usr/include/openssl/ossl_typ.h:116:16: note: forward declaration of 'struct dh_st'
typedef struct dh_st DH;
               ^
4 errors generated.
*** Error 1 in /home/eradman/.gem/ruby/3.1/gems/puma-5.6.4/ext/puma_http11 (Makefile:246 'mini_
ssl.o': @ cc -I. -I/usr/local/include/ruby-3....)

make failed, exit code 2
```

**To Reproduce**

```
gem31 install puma
```

**Comment by MSP-Greg** [comment]
@eradman  Thanks for the report.

Can you try building from PR https://github.com/puma/puma/pull/2864?

**Comment by eradman** [comment]
Thanks for the quick response @MSP-Greg!

I actually don't hit the same error when trying to build from top of tree

```
git log -1 --oneline
0f6ab127 (HEAD -> master, origin/master, origin/HEAD) [CI] minor workflow updates
```

```
cd puma/ext/puma_http11
doas bundle31 exec rake31
(in /home/eradman/git.oss/puma)
Running RuboCop...
Inspecting 160 files
................................................................................................................................................................

160 files inspected, no offenses detected
mkdir -p tmp/x86_64-openbsd/puma_http11/3.1.1
cd tmp/x86_64-openbsd/puma_http11/3.1.1
/usr/local/bin/ruby31 -I. -r.rake-compiler-siteconf.rb ../../../../ext/puma_http11/extconf.rb
using OpenSSL pkgconfig (openssl.pc)
checking for openssl/bio.h... yes
checking for DTLS_method() in openssl/ssl.h... yes
checking for TLS_server_method() in openssl/ssl.h... yes
checking for SSL_CTX_set_min_proto_version(NULL, 0) in openssl/ssl.h... yes
checking for X509_STORE_up_ref()... yes
checking for SSL_CTX_set_ecdh_auto(NULL, 0) in openssl/ssl.h... yes
checking for SSL_get1_peer_certificate() in openssl/ssl.h... no
checking for Random.bytes... yes
creating Makefile
cd -
cd tmp/x86_64-openbsd/puma_http11/3.1.1
/usr/local/bin/gmake
compiling ../../../../ext/puma_http11/http11_parser.c
compiling ../../../../ext/puma_http11/mini_ssl.c
compiling ../../../../ext/puma_http11/puma_http11.c
linking shared-object puma/puma_http11.so
cd -
mkdir -p tmp/x86_64-openbsd/stage/lib/puma
```

**Comment by MSP-Greg** [comment]
@eradman Thanks for checking, I think PR #2838 fixed it.

PR #2864 may still be an improvement.  @epsilon-0 @botovq Sorry for the pings, any thoughts?

**Comment by botovq** [comment]
On Mon, Apr 25, 2022 at 04:03:29PM -0700, MSP-Greg wrote:
> @eradman Thanks for checking, I think PR #2838 fixed it.

Yes, a version of this patch is needed for LibreSSL 3.5 and later for
Puma up to and including 5.6.4 - OpenBSD 7.1 has LibreSSL 3.5.2.

> PR #2864 may still be an improvement.  @epsilon-0 @botovq Sorry for the pings, any thoughts?

Yes, definitely an improvement. This will work with LibreSSL as well.
Thanks!

**Comment by MSP-Greg** [comment]
@botovq Thanks.

Currently Puma does not work with TLS session reuse or ALPN.  We'll be adding support for both soon.  I suspect reuse will need to be turned on to match current functionality, ALPN may be the same.

I assume LibreSSL should/will work with the OpenSSL functions?  Would you like a ping on the PR's?

**Comment by botovq** [comment]
@MSP-Greg I am not worried, but I will happily look over the PR.
