### ISSUE TITLE
Puma's capistrano recipe doesn't work with capistrano 3.0.0

### ISSUE THREAD

**Issue by nateless** [puma/puma#383]
```
~/Ruby/devhub(branch:master*) » cap -vT                                                                                                                                         nate@nateless
cap aborted!
undefined method `instance' for Capistrano::Configuration:Class
/Users/nate/.rvm/gems/ruby-2.0.0-p195/gems/puma-2.6.0/lib/puma/capistrano.rb:1:in `<top (required)>'
```
