### ISSUE TITLE
Unable to load application

### ISSUE THREAD

**Issue by Casara** [puma/puma#913]
When upgrading from version 2.16.0 to 3.0.2 this happened:
```
[5102] Puma starting in cluster mode...
[5102] * Version 3.0.2 (ruby 2.3.0-p0), codename: Plethora of Penguin Pinatas
[5102] * Min threads: 1, max threads: 6
[5102] * Environment: development
[5102] * Process workers: 1
[5102] * Preloading application
[5102] ! Unable to load application: NoMethodError: undefined method `fetch' for #<Puma::LeveledOptions:0x00000002ffa8a0>
```

**Comment by evanphx** [comment]
Are you doing '@options.fetch' in your config file?

**Comment by Casara** [comment]
I had the following code in an initializer:
```ruby
Puma.cli_config.options.fetch(:max_threads)
```
So I did the following:
```ruby
Puma.cli_config.options[:max_threads]
```
But Anyway thanks!

**Comment by evanphx** [comment]
@Casara Why are you reading the max threads? Also, in 3.0+, you can do `get(:max_threads)` in the config files to read that value.

**Comment by Casara** [comment]
@evanphx I'm reading the max threads to set ActiveRecord connection pool size: [UPDATED - Setting ActiveRecord's connection pool size on Heroku with Puma or Sidekiq](http://jc00ke.com/2014/01/09/updated-ar-connection-pool-size-on-heroku-with-puma-and-sidekiq/).
