### ISSUE TITLE
2.12 failed to compile in mingw platform, but 2.11.3 works.

### ISSUE THREAD

**Issue by Eric-Guo** [puma/puma#733]
I can following [previous version of successful methods](http://blog.cloud-mes.com/2014/10/06/compile-eventmachine-1-dot-0-3-in-ruby-2-dot-1-3-on-windows/) to compile at puma v2.11.3

```bat
c:\Temp>gem install puma -v2.11.3 -- --with-opt-dir=c:\temp --with-opt-lib=c:\temp\lib
Building native extensions with: '--with-opt-dir=c:\temp --with-opt-lib=c:\temp\lib'
This could take a while...
Successfully installed puma-2.11.3
1 gem installed
```

But for 2.12.0, have problem of `mini_ssl.c:215: undefined reference to `strerror_r'`

```
C:/Ruby21/bin/ruby.exe -r ./siteconf20150715-5572-hu09iw.rb extconf.rb --with-opt-dir=c:\temp --with-opt-lib=c:\temp\lib
checking for BIO_read() in -lcrypto... yes
checking for SSL_CTX_new() in -lssl... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
generating puma_http11-i386-mingw32.def
compiling http11_parser.c
ext/http11/http11_parser.rl: In function 'puma_parser_execute':
ext/http11/http11_parser.rl:111:3: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
compiling io_buffer.c
io_buffer.c: In function 'buf_to_str':
io_buffer.c:119:3: warning: pointer targets in passing argument 1 of 'rb_str_new' differ in signedness [-Wpointer-sign]
In file included from c:/Ruby21/include/ruby-2.1.0/ruby/ruby.h:1694:0,
                 from c:/Ruby21/include/ruby-2.1.0/ruby.h:33,
                 from io_buffer.c:2:
c:/Ruby21/include/ruby-2.1.0/ruby/intern.h:704:7: note: expected 'const char *' but argument is of type 'uint8_t *'
compiling mini_ssl.c
In file included from mini_ssl.c:3:0:
c:/Ruby21/include/ruby-2.1.0/ruby/backward/rubyio.h:2:2: warning: #warning use "ruby/io.h" instead of "rubyio.h" [-Wcpp]
mini_ssl.c: In function 'engine_init_server':
mini_ssl.c:147:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
mini_ssl.c:150:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
mini_ssl.c: In function 'raise_error':
mini_ssl.c:215:5: warning: implicit declaration of function 'strerror_r' [-Wimplicit-function-declaration]
mini_ssl.c: In function 'engine_read':
mini_ssl.c:242:14: warning: unused variable 'n' [-Wunused-variable]
mini_ssl.c: In function 'engine_peercert':
mini_ssl.c:341:3: warning: pointer targets in passing argument 1 of 'rb_str_new' differ in signedness [-Wpointer-sign]
In file included from c:/Ruby21/include/ruby-2.1.0/ruby/ruby.h:1694:0,
                 from c:/Ruby21/include/ruby-2.1.0/ruby.h:33,
                 from mini_ssl.c:2:
c:/Ruby21/include/ruby-2.1.0/ruby/intern.h:704:7: note: expected 'const char *' but argument is of type 'unsigned char *'
compiling puma_http11.c
linking shared-object puma/puma_http11.so
mini_ssl.o: In function `raise_error':
C:\Ruby21\lib\ruby\gems\2.1.0\gems\puma-2.12.0\ext\puma_http11/mini_ssl.c:215: undefined reference to `strerror_r'
collect2.exe: error: ld returned 1 exit status
make: *** [puma_http11.so] Error 1

make failed, exit code 2
```

**Comment by Eric-Guo** [comment]
Really fast fix, confirm work, thanks.
