### ISSUE TITLE
pumactl -P path stop not working in 3.8.0

### ISSUE THREAD

**Issue by saubi1993** [puma/puma#1242]
### Steps to reproduce

On executing 'pumactl -P path stop' it throws following error

undefined method `from_file' for Puma::Configuration:Class

### Expected behavior

on stop puma should stop, start should start

### Actual behavior

pumactl stop start retsrat not working

### System configuration

**Ruby version**: 2.2.5
**Rails version**: 4.1.8

**Comment by nateberkopec** [comment]
Please upgrade to 3.8.1.

**Comment by saubi1993** [comment]
Thanks
